version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGIT2507Project
  gitServerName: Kusi_VCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqagit2507.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQAGIT2507Project
    version: "1.0"
- serviceName: project.siqagit2507.integrations:JMSFlowTest
  packages:
  - name: SIQAGIT2507Project
    version: "1.0"
- serviceName: publisher:publisher
  packages:
  - name: JMSTest
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.7
- serviceName: project.siqagit2507.integrations:JMS_JNDI_SSL
  packages:
  - name: SIQAGIT2507Project
    version: "1.0"
- serviceName: project.siqagit2507.integrations:SIQAAdapterFlow
  packages:
  - name: SIQAGIT2507Project
    version: "1.0"
