version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGIT2507Project
  gitServerName: Kusi_VCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqagit2507.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQAGIT2507Project
    version: "1.0"
- serviceName: project.siqagit2507.integrations:SIQAAdapterFlow
  packages:
  - name: SIQAGIT2507Project
    version: "1.0"
